In [1]:
#Importing dependencies
import numpy as np 
import pandas as pd 
import plotly as py
import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [14]:
#Importing CSV
df = pd.read_csv('Data Sources\covid_19_data.csv')
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
12244,12245,04/05/2020,Wyoming,US,2020-04-05 23:13:44,197.0,0.0,0.0
12245,12246,04/05/2020,Xinjiang,Mainland China,2020-04-05 23:13:44,76.0,3.0,73.0
12246,12247,04/05/2020,Yukon,Canada,2020-04-05 23:13:44,6.0,0.0,0.0
12247,12248,04/05/2020,Yunnan,Mainland China,2020-04-05 23:13:44,184.0,2.0,172.0
12248,12249,04/05/2020,Zhejiang,Mainland China,2020-04-05 23:13:44,1263.0,1.0,1230.0

In [6]:
#column renaming for easier manipulations
df = df.rename(columns={'Country/Region':'Country'})
df = df.rename(columns={'ObservationDate':'Date'})
df.head()

,SNo,Date,Province/State,Country,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [12]:
#Dataframe Manipulation
df_countries = df.groupby(['Country', 'Date']).sum().reset_index().sort_values('Date', ascending=False)
df_countries = df_countries.drop_duplicates(subset = ['Country'])
df_countries = df_countries[df_countries['Confirmed']>0]
df_countries

                  Country        Date    SNo  Confirmed  Deaths  Recovered
415            Azerbaijan  04/05/2020  11940      584.0     7.0       32.0
1218  Congo (Brazzaville)  04/05/2020  11966       45.0     5.0        2.0
4707                Qatar  04/05/2020  12063     1604.0     4.0      123.0
430               Bahamas  04/05/2020  11941       28.0     4.0        0.0
4137          New Zealand  04/05/2020  12048     1039.0     1.0      156.0
...                   ...         ...    ...        ...     ...        ...
4424            Palestine  03/09/2020   4322       22.0     0.0        0.0
6277         Vatican City  03/09/2020   4507        1.0     0.0        0.0
4708  Republic of Ireland  03/08/2020   4067       21.0     0.0        0.0
0              Azerbaijan  02/28/2020   2664        1.0     0.0        0.0
4211        North Ireland  02/28/2020   2685        1.0     0.0        0.0

[209 rows x 6 columns]